### PR TITLE
Update legal document v5

### PR DESCRIPTION
**Pull request by Irma12**
Preview: https://deploy-preview-1186--roadie.netlify.app/legal-notices/terms-of-service/v5/

### CODE REVIEW

**Review by oblongcoffee — CHANGES_REQUESTED** [review]
It's great to see this getting updated 😄  I spotted three issues but the rest looks good! 

1. 
There is an extra legal definition in the Data Processing Addendum that shouldn't be there, this text should be removed from the "DPA definitions":
"Data Protection Laws: any data protection laws applicable to processing of Personal Data contemplated by this agreement including, without limitation, in particular the European Union General Data Protection Regulation (“GDPR”), the European Union Directive on Privacy and Electronic Communications (“E-Privacy Directive”), the UK’s Data Protection Act 2018 and any related decisions or guidelines and subsequent legislation of a similar nature, and all privacy, security, and data protection laws, rules, and regulations of any applicable jurisdiction including any jurisdiction in which the or Professional Services are being provided or the Personal Data is being processed and any jurisdiction from which Roadie or any subprocessor provides any of the or Professional Services or from which Customer provides Customer’s products or services."

2.
The formatting in “12 RESTRICTED TRANSFERS” 12.2.1 in the DPA is a bit off. It should be listed as a list like:
“(i)
(ii)
(iii)….”
Right now it is like “(i)…(ii)…(iii)….”
This is the same for 12.2.2 and 12.3.1. and 12.3.2. They should all be updated 

3.
In the last table “C. Competent Supervisory Authority” the second row formatting is incorrect. The text on row two “Where the UK GDPR applies, the competent supervisory authority shall be the UK Information Commissioner’s Office” should be in the the right-hand side column, it is currently in the left hand side column.

**Comment by Irma12** [comment]
@oblongcoffee Thanks for looking into it and catching extra things. There was something I noticed in document as well. maybe worth fixing it here and there as well, if it is relevant?

  We are missing (ix) and instead have I, II, III, V

Screenshot 2023-12-14 at 10 56 15
Screenshot 2023-12-14 at 10 56 06

**Review by oblongcoffee — CHANGES_REQUESTED** [review]
@Irma12 Yes you are correct about the (v), they should read (i)(ii)(iii)(iv)(v). Would you mind updated this in 12.3.2 and 12.3.1?

I also spotted two minor issues 👇 
(ii) is still on the same line as (i):
Screenshot 2023-12-14 at 16 51 29

There is a "/" at the end of this paragraph:
Screenshot 2023-12-14 at 16 51 59

**Comment by Irma12** [comment]
@oblongcoffee Awesome! Fixed, should be ok now :)

**Review by oblongcoffee — APPROVED** [review]
Looking good! 😄

**Pull request merged**
