### PR TITLE
Create v4.md

### PR DESCRIPTION
**Pull request by oblongcoffee**
Adding Auth0

### CODE REVIEW

**Review by dtuite — APPROVED** [review]

**Comment by oblongcoffee** [comment]
@dtuite  This has not appeared on the website, I think I must have forgot something in the PR.

**Comment by oblongcoffee** [comment]
> @oblongcoffee netlify is having issues at the moment

😅

**Comment by oblongcoffee** [comment]
@dtuite  I don't think it worked. It seems to have reverted back to an earlier version, Intercom is missing now

Screenshot 2021-08-24 at 17 01 17

**Comment by oblongcoffee** [comment]
> @dtuite I don't think it worked. It seems to have reverted back to an earlier version, Intercom is missing now
> 
> Screenshot 2021-08-24 at 17 01 17

Intercom is actually back now and you can see v4 live here: https://roadie.io/legal-notices/sub-processors/v4/

but when you click this 👇  it brings you to v3
Screenshot 2021-08-24 at 17 05 12

I am not sure how to fix this.

**Comment by dtuite** [comment]
@oblongcoffee It's working for me. Try incognito mode.

**Comment by oblongcoffee** [comment]
> @oblongcoffee It's working for me. Try incognito mode.

ah, that works!

**Pull request merged**
