### PR TITLE
Update GraphiQL plugin doc

### PR DESCRIPTION
**Pull request by briandesousa**
Refresh GraphiQL plugin documentation. Expand the document to demonstrate different ways to integrate GraphQL endpoints into the GraphiQL page in Backstage, including and example that uses the GitHub auth API.

### CODE REVIEW

**Comment by briandesousa** [comment]
It looks like some of the "Intro" text from the markdown didn't render on the GraphiQL page on the [Netlify deploy preview](https://deploy-preview-260--roadie.netlify.app/backstage/plugins/graphiQL/). Have you seen this before @dtuite?

**Comment by dtuite** [comment]
> It looks like some of the "Intro" text from the markdown didn't render on the GraphiQL page on the [Netlify deploy preview](https://deploy-preview-260--roadie.netlify.app/backstage/plugins/graphiQL/). Locally it renders ok for me. Have you seen this before @dtuite?

Super weird. I can see the content flash on the page before something removes it. I can't reproduce this locally. It's going to take me some time to look into this. We can merge it before we figure this out because even without the intro sections it's better than the content currently live.

One small request. Could you show the user how to add a sidebar item which brings them to the GraphiQL page please? Other than that, I think this is ready to ship.

**Comment by briandesousa** [comment]
> One small request. Could you show the user how to add a sidebar item which brings them to the GraphiQL page please? Other than that, I think this is ready to ship.

Added step to add link to the sidebar.

**Review by dtuite — APPROVED** [review]
Great job figuring out those nested p tags!

**Pull request merged**
