### PR TITLE
Add Cloudsmith to the plugin list

### PR DESCRIPTION
**Pull request by BartoszBlizniak**
Adding Cloudsmith to the plugin list for Roadie.

### CODE REVIEW

**Comment by jorgelainfiesta** [comment]
Thanks for your contribution @BartoszBlizniak! Roadie haven't implemented support for the Cloudsmith plugin through our Admin UI, so we cannot merge yet half of your PR.

Could you please split this PR so we can merge the part that belongs to the marketplace already? We'll merge in the Roadie docs once we've finished implementing support for your plugin.

**Comment by BartoszBlizniak** [comment]
Hey @jorgelainfiesta - I have removed the docs accordingly, I will update the branch once this has been merged, thanks!

**Comment by BartoszBlizniak** [comment]
Hey @jorgelainfiesta - looks like one of the tests here is failing, I tried running `yarn build` on the `main` branch as well and it's failing, just wanted to confirm if there is any action on my side here?

**Comment by jorgelainfiesta** [comment]
I'm looking into it @BartoszBlizniak, thanks!

**Review by jorgelainfiesta — APPROVED** [review]
I noticed our current setup doesn't complete the missing secrets for PRs coming from people outside the Roadie org; apologies for that. Your page should render correctly when merged into main. 

I added a `.png` version of your logo as the `svg` wouldn't render well on the page. Thanks @BartoszBlizniak !

**Pull request merged**
