### PR TITLE
Add documentation for roadie api

### PR DESCRIPTION
**Pull request by punkle**

### CODE REVIEW

**Review by sblausten — APPROVED** [review]
Nice one. Have we released the self service token generation yet though? Maybe we need to wait to merge this until thats done if not

**Review by samnixon87 — APPROVED** [review]
Nice. Same comment as @sblausten - we should time this with the launch of self-serve token generation.

**Comment by Xantier** [comment]
Was this merge premature?

**Comment by kissmikijr** [comment]
I think so

**Comment by punkle** [comment]
@Xantier @kissmikijr why was it premature? My understanding was that we were including the docs in the launch silently step: https://roadiehq.slack.com/archives/CUFAGVDDG/p1705410608282399

**Pull request merged**
