### PR TITLE
Add the Pulumi plugin

### PR DESCRIPTION
**Pull request by ringods**

### CODE REVIEW

**Comment by dtuite** [comment]
Thanks for this. We'll take a look and get this merged.

\cc @jorgelainfiesta

**Review by jorgelainfiesta — APPROVED** [review]
We had agreed with Isaac, this page is to be merged until the night prior to Pulumi's press release on October 11th

**Comment by jorgelainfiesta** [comment]
Merging as the plugin was already released an published to Backstage's marketplace

**Comment by isaac-pulumi** [comment]
Thanks @jorgelainfiesta!

**Pull request merged**
