### PR TITLE
Removes unnecesary packages and migrates events to new tag

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
The custom event tracking implementation was using the legacy Google Analytics package. 

I ended up doing the tracking on the website instead of Zapier to keep the browser context.

TODO

- [x] Remove legacy packages
- [x] Add tracking for request demo
- [x] Add tracking for request trial
- [x] Add tracking for subscribe (various places)

### CODE REVIEW

**Comment by jorgelainfiesta** [comment]
I'm having trouble with a `Link` unit test. I simply changed `OutboundLink` to use `gatsby-plugin-google-gtag` implementation instead of the old GA plugin. 

The test fails with:
```
1) Link
[49](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:50)
       should return an OutboundLink for external links:
[50](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:51)

[51](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:52)
      AssertionError: expected 'ForwardRef' to equal 'OutboundLink'
[52](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:53)
      + expected - actual
[53](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:54)

[54](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:55)
      -ForwardRef
[55](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:56)
      +OutboundLink
[56](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:57)
      
[57](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:58)
      at Context.<anonymous> (src/components/Link/Link.test.js:37:31)
[58](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:59)
      at processImmediate (node:internal/timers:476:21)
```

I'm not familiar with this kind of unit test, any pointers?

**Comment by dtuite** [comment]
> I'm having trouble with a `Link` unit test. I simply changed `OutboundLink` to use `gatsby-plugin-google-gtag` implementation instead of the old GA plugin.
> 
> The test fails with:
> 
> ```
> 1) Link
> [49](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:50)
>        should return an OutboundLink for external links:
> [50](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:51)
> 
> [51](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:52)
>       AssertionError: expected 'ForwardRef' to equal 'OutboundLink'
> [52](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:53)
>       + expected - actual
> [53](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:54)
> 
> [54](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:55)
>       -ForwardRef
> [55](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:56)
>       +OutboundLink
> [56](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:57)
>       
> [57](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:58)
>       at Context.<anonymous> (src/components/Link/Link.test.js:37:31)
> [58](https://github.com/RoadieHQ/marketing-site/actions/runs/5856618426/job/15876744374?pr=1089#step:7:59)
>       at processImmediate (node:internal/timers:476:21)
> ```
> 
> I'm not familiar with this kind of unit test, any pointers?

I fixed it for you.

**Comment by jorgelainfiesta** [comment]
Thank you! and indeed, I tested the events are going to GA

**Comment by dtuite** [comment]
I deleted the test so this should be working for you now.

**Pull request merged**
