### PR TITLE
Delete unused images

### PR DESCRIPTION
**Pull request by dtuite**
My theory is that [gatsby-transformer-sharp](https://www.gatsbyjs.com/plugins/gatsby-transformer-sharp/) is transforming all images in the assets directory, even if they are never actually used on the site. This is leading to 14 minutes in the build spent optimizing images.

```
2:02:49 PM: success Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 857.482s - 745/745 0.87/s
```

Querying the image sharp images returns every image in the assets directory. Including those which are not used.

```
  allImageSharp {
    nodes {
      fixed {
        originalName
      }
    }
  }
```

If this build is materially faster, we have a smoking gun.

### CODE REVIEW

**Comment by dtuite** [comment]
```
11:48:30 PM: success Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 737.274s - 755/755 1.02/s
```

2 mins shaved off. Not bad

**Comment by dtuite** [comment]
https://app.shortcut.com/larder/stories/new

**Comment by dtuite** [comment]
Down to 16 minutes with the Contentful blog migration rebased in.

**Comment by Xantier** [comment]
> Down to 16 minutes with the Contentful blog migration rebased in.

Down to 16 from 14?

**Review by Xantier — APPROVED** [review]

**Comment by dtuite** [comment]
The 14 was just the image processing stage of the build. The whole build is longer.

16 mins is a measure of the whole build.

**Pull request merged**
