### PR TITLE
Adding docs for snyk

### PR DESCRIPTION
**Pull request by nicolasarnold12321**

### CODE REVIEW

**Comment by nicolasarnold12321** [comment]
https://deploy-preview-325--roadie.netlify.app/docs/integrations/snyk/ <- rendered page

**Review by dtuite — APPROVED** [review]
Thanks for linking directly to the page. Appreciate it!

**Comment by dtuite** [comment]
[ch2140]

**Comment by nicolasarnold12321** [comment]
No problem. Thanks for the review

**Pull request merged**
