### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by punkle**

### CODE REVIEW

**Comment by Xantier** [comment]
Can you also fix the link to point to a location where the plugin is moved into

**Comment by punkle** [comment]
@Xantier I dont understand what you mean.

**Comment by Xantier** [comment]
Mentioned in this comment: https://roadiehq.slack.com/archives/C04RMF85203/p1683206048358559

**Comment by punkle** [comment]
I still dont think I understand. I have added the app-selector annotation also.

**Review by sblausten — APPROVED** [review]

**Pull request merged**
