### PR TITLE
Add looping example

### PR DESCRIPTION
**Pull request by punkle**

### CODE REVIEW

**Review by dtuite — COMMENTED** [review]
It's going to be pretty buried in here. Would the [recipies section](https://roadie.io/docs/scaffolder/debug-template/) not be a better place?

**Comment by punkle** [comment]
@dtuite how about this https://deploy-preview-1215--roadie.netlify.app/docs/scaffolder/loops-in-steps/

**Review by Xantier — COMMENTED** [review]
Maybe worth updating the existing looping recipe with a link to this or add this info to it directly

**Comment by punkle** [comment]
@Xantier done thanks.

**Review by dtuite — APPROVED** [review]

**Pull request merged**
