### PR TITLE
remove unreferenced images

### PR DESCRIPTION
**Pull request by punkle**
Removing a lot of images that do not appear to be referenced in the project anymore.. I left the images in the static directory, in case they are referenced externally.

Please test my assumptions on this pull request.

here was my process:

- list images tracked by git
- get the base name
- grep js, html and md files for that basename
- delete the image if its not in any of those files unless its under the static directory

### CODE REVIEW

**Review by Xantier — COMMENTED** [review]
> Please test my assumptions on this pull request.

image

:cold_sweat: 

What's the process of testing these assumptions? Click through the marketing site?

**Comment by punkle** [comment]
@Xantier here was my process:

- list images tracked by git
- get the base name
- grep js, html and md files for that basename
- delete the image if its not in any of those files

**Review by Ian-Link-Roadie — APPROVED** [review]

**Comment by roadgork** [comment]
Tested it properly and it's correct. Reference: https://roadiehq.slack.com/archives/C07HU5GDKU1/p1724932448649349?thread_ts=1724856766.197989&cid=C07HU5GDKU1

**Review by roadgork — APPROVED** [review]
It's correct. These files are not referenced in the code

**Pull request merged**
